# Learn more about this config here: https://pre-commit.com/

# To enable these pre-commit hooks run:
# `brew install pre-commit` or `python3 -m pip install pre-commit`
# Then in the project root directory run `pre-commit install`

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: end-of-file-fixer
      exclude: |
          (?x)^(
              ^docs/licenses/.*$
              | ^.*\.svg$
              | ^.*\.sfd$
              | docs/LGPL.txt
              | subprojects/.*
          )$
    - id: trailing-whitespace
      exclude: |
          (?x)^(
              ^docs/licenses/.*$
              | ^.*\.svg$
              | ^.*\.sfd$
              | docs/LGPL.txt
              | subprojects/.*
          )$

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:  # See pyproject.toml for configuration options.
      - id: ruff
        name: ruff-sort-imports
        args: [ --select, I, --fix ]
      - id: ruff-format  # Run the formatter
        types_or: [ python, pyi, jupyter ]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
      - id: clang-format
        exclude: |
            (?x)^(
                ^src_c/_sdl2/.*$
                | ^src_c/doc/.*$
                | docs/reST/_static/script.js
                | docs/reST/_templates/header.h
                | src_c/include/sse2neon.h
                | src_c/include/pythoncapi_compat.h
                | src_c/pypm.c
                | subprojects/.*
            )$
